#### CRANE UP
PUT http://localhost:57190/api/crane/position/ HTTP/1.1
content-type: application/json

{
    "up": true
}

#### CRANE DOWN
PUT http://localhost:57190/api/crane/position/ HTTP/1.1
content-type: application/json

{
    "up": false
}

#### CRANE EXTEND
PUT http://localhost:57190/api/crane/extend/ HTTP/1.1
content-type: application/json

{
    "up": true
}

#### CRANE RETRACT
PUT http://localhost:57190/api/crane/extend/ HTTP/1.1
content-type: application/json

{
    "up": false
}


#### ROPE RETRACT
PUT http://localhost:57190/api/crane/rope/extend/ HTTP/1.1
content-type: application/json

{
    "up": false
}

#### ROPE EXTEND
PUT http://localhost:57190/api/crane/rope/extend/ HTTP/1.1
content-type: application/json

{
    "up": true
}

#### GET HUBS
GET http://localhost:57190/api/crane/hubs/ HTTP/1.1
content-type: application/json