#### CRANE UP
PUT http://localhost:57190/api/crane/position/ HTTP/1.1
content-type: application/json

{
    "up": true
}

#### CRANE DOWN
PUT http://localhost:57190/api/crane/position/ HTTP/1.1
content-type: application/json

{
    "up": false
//    ,"stop": 150
}

#### CRANE EXTEND
PUT http://localhost:57190/api/crane/extend/ HTTP/1.1
content-type: application/json

{
    "out": true,
    "duration": 10000
}

#### CRANE RETRACT
PUT http://localhost:57190/api/crane/extend/ HTTP/1.1
content-type: application/json

{
    "out": false,
    "duration": 10000
}


#### ROPE RETRACT
PUT http://localhost:57190/api/crane/rope/extend/ HTTP/1.1
content-type: application/json

{
    "out": false,
    "duration": 5000
}

#### ROPE EXTEND
PUT http://localhost:57190/api/crane/rope/extend/ HTTP/1.1
content-type: application/json

{
    "out": true,
    "duration": 5000
}

### RUN PUMP
PUT http://localhost:57190/api/crane/pump/ HTTP/1.1
content-type: application/json

{
    "duration": 10000
}

### STABILIZERS EXTEND
PUT http://localhost:57190/api/crane/stabilizers/ HTTP/1.1
content-type: application/json

{
    "duration": 2000,
    "out": true
}

### STABILIZERS RETRACT
PUT http://localhost:57190/api/crane/stabilizers/ HTTP/1.1
content-type: application/json

{
    "duration": 3000,
    "out": false
}

### STABILIZERS TEST
PUT http://localhost:57190/api/crane/stabilizers/test-down HTTP/1.1
content-type: application/json

{
//    "duration": 3000,
    "out": true
}

### PARAPET TURN
PUT http://localhost:57190/api/crane/parapet/ HTTP/1.1
content-type: application/json

{
    "duration": 1000
}

### DRIVE
PUT http://localhost:57190/api/crane/drive/ HTTP/1.1
content-type: application/json

{
    "duration": 0
}

#### GET HUBS
GET http://localhost:57190/api/crane/hubs/ HTTP/1.1
content-type: application/json